### ISSUE TITLE
Bump UNWPP data to 2022 Projections

### ISSUE THREAD

**Issue by beansrowning** [CDCgov/SaviR#82]
Out of alignment with OWID

## TODO
- [x] Merge #81
- [x] Write out updated onetable CSV to datalake
- [x] Update SaviR version on all automated products
  - [x] CAOC Dashboard (https://github.com/cdcent/caoc-shiny-dashboard/issues/7)
  - [x] DUB (https://github.com/cdcent/ITF-SAVI-DUB-PPT/issues/117)
  - [x] Internal / External Dashboard Update repos (https://github.com/CDCgov/ITF-Dashboard/issues/3, https://github.com/CDCgov/ITF_Power_BI/issues/11)
- [x] Send an announcement to team

**Comment by beansrowning** [comment]
Datalake updated https://github.com/CDCgov/ITF-Dashboard/actions/runs/3576774278
